base_config:
- config/logging.yaml

dataloader:
  num_workers: 8
  pin_memory: true
  train_batch_size: 20
  val_batch_size: 20
  test_batch_size: 48
  seed: 2024  # to ensure continuity when resuming from checkpoint

# Training settings
trainer:
  init_seed: 2024  # use null to train w/o seeding
  save_period: 100
  backup_period: 2000

gt_depth_type: depth_raw_linear
gt_mask_type: valid_mask_raw

max_epoch: 5  # a large enough number
max_iter: 10000  # usually converges at around 20k

model:
  name: MiDas
  backbone: resnext101_wsl

dataset:
  train:
    name: vkitti2
    disp_name: vkitti2_train
    dir: vkitti2
    filenames: data_split/vkitti2_train.txt
    kitti_bm_crop: true
    valid_mask_crop: null  # no valid_mask_crop for training
    norm_name: vkitti2
    resize_to_hw:
    - 160
    - 544
  val:
    name: vkitti2
    disp_name: vkitti2_val
    dir: vkitti2
    filenames: data_split/vkitti2_val.txt
    kitti_bm_crop: true
    valid_mask_crop: eigen
    norm_name: vkitti2
    resize_to_hw:
    - 160
    - 544
  test:
    - name: vkitti2
      disp_name: vkitti2_test
      dir: vkitti2
      filenames: data_split/vkitti2_test.txt
      kitti_bm_crop: True
      valid_mask_crop: eigen
      norm_name: vkitti2
      resize_to_hw:
      - 160
      - 544

depth_normalization:
  type: scale_shift_depth
  clip: true
  norm_min: -1.0
  norm_max: 1.0
  min_max_quantile: 0.02

augmentation_args:
  random_horizontal_flip:
    in_use: true
    p: 0.5
  jitter:
    in_use: true
    p: 0.25
    args:
      hue: 0.1
      brightness: 0.1
      contrast: 0.1
  cutdepth:
    in_use: true
    p: 0.5
    depth_type: linear
    par: 0.5
  red_green_channel_swap:
    in_use: true
    p: 0.25

optimizer:
  name: AdamW

loss:
  name: mixed

lr_pretrained: 3.0e-05
lr_scratch: 3.0e-03

# lr_scheduler:
#   name: IterExponential
#   kwargs:
#     total_iter: 25000
#     final_ratio: 3.0e-010
#     warmup_steps: 1000

# Validation settings
validation:
  main_val_metric: abs_relative_difference
  main_val_metric_goal: minimize
  init_seed: 2024

eval:
  alignment: least_square
  align_max_res: null
  eval_metrics:
  - abs_relative_difference
  - squared_relative_difference
  - rmse_linear
  - rmse_log
  - log10
  - delta1_acc
  - delta2_acc
  - delta3_acc
  - i_rmse
  - silog_rmse
