base_config:
- config/logging.yaml
- config/wandb.yaml
- config/model_sdv2.yaml

dataset:
  train:
    name: nyu_v2
    disp_name: nyu_v2
    dir: nyu_v2
    filenames: data_split/nyu_2_paths1.txt
    eigen_valid_mask: true
    norm_name: nyu
    resize_to_hw:
    - 128
    - 128
  val:
    name: nyu_v2
    disp_name: nyu_v2
    dir: nyu_v2
    filenames: data_split/nyu_2_paths1.txt
    eigen_valid_mask: true
    norm_name: nyu
    resize_to_hw:
    - 128
    - 128
  test:
    - name: nyu_v2
      disp_name: nyu_v2
      dir: nyu_v2
      filenames: data_split/nyu_2_paths1.txt
      eigen_valid_mask: true
      norm_name: nyu
      resize_to_hw:
      - 128
      - 128

model:
  name: TernausNet
  backbone: vgg16

depth_normalization:
  type: scale_shift_depth
  clip: true
  norm_min: 0.000001
  norm_max: 1.0
  min_max_quantile: 0.01

augmentation_args:
  random_horizontal_flip:
    in_use: true
    p: 0.5
  jitter:
    in_use: true
    p: 0.5
    args:
      hue: 0.1
      brightness: 0.1
      contrast: 0.1
  cutdepth:
    in_use: true
    p: 0.5
    depth_type: linear
    par: 0.5
  red_green_channel_swap:
    in_use: true
    p: 0.5

dataloader:
  num_workers: 0
  train_batch_size: 5
  val_batch_size: 5
  test_batch_size: 5
  seed: 2024  # to ensure continuity when resuming from checkpoint

# Training settings
trainer:
  init_seed: 2024  # use null to train w/o seeding
  save_period: 10
  backup_period: 2000

gt_depth_type: depth_raw_norm
gt_mask_type: valid_mask_raw

max_epoch: 10  # a large enough number
max_iter: 100  # usually converges at around 20k

optimizer:
  name: SGD

loss:
  name: mse_loss
  kwargs:
    reduction: mean

lr: 3.0e-05

lr_scheduler:
  name: IterExponential
  kwargs:
    total_iter: 25000
    final_ratio: 0.01
    warmup_steps: 100

# Validation settings
validation:
  main_val_metric: abs_relative_difference
  main_val_metric_goal: minimize
  init_seed: 2024

eval:
  eval_metrics:
  - abs_relative_difference
  - squared_relative_difference
  - rmse_linear
  - rmse_log
  - log10
  - delta1_acc
  - delta2_acc
  - delta3_acc
  - i_rmse
  - silog_rmse
