base_config:
- config/logging.yaml

dataloader:
  num_workers: 0
  pin_memory: true
  train_batch_size: 8
  val_batch_size: 8
  test_batch_size: 48
  seed: 2024  # to ensure continuity when resuming from checkpoint

# Training settings
trainer:
  init_seed: 2024  # use null to train w/o seeding
  save_period: 50
  backup_period: 2000

gt_depth_type: depth_raw_linear
gt_mask_type: valid_mask_raw

max_epoch: 10  # a large enough number
max_iter: 10000  # usually converges at around 20k

model:
  name: TernausNet
  backbone: vgg116

dataset:
  train:
    name: nyu_v2
    disp_name: nyu_v2
    dir: nyu_v2
    filenames: data_split/nyu_2_paths_train.txt
    eigen_valid_mask: true
    norm_name: nyu
    resize_to_hw:
    - 128
    - 128
  val:
    name: nyu_v2
    disp_name: nyu_v2
    dir: nyu_v2
    filenames: data_split/nyu_2_paths_val.txt
    eigen_valid_mask: true
    norm_name: nyu
    resize_to_hw:
    - 128
    - 128
  test:
    - name: nyu_v2
      disp_name: nyu_v2
      dir: nyu_v2
      filenames: data_split/nyu_2_paths_test.txt
      eigen_valid_mask: true
      norm_name: nyu
      resize_to_hw:
      - 128
      - 128

depth_normalization:
  type: scale_shift_depth
  clip: true
  norm_min: -1
  norm_max: 1
  min_max_quantile: 0.02

augmentation_args:
  random_horizontal_flip:
    in_use: true
    p: 0.5
  jitter:
    in_use: true
    p: 0.25
    args:
      hue: 0.1
      brightness: 0.1
      contrast: 0.1
  cutdepth:
    in_use: true
    p: 0.5
    par: 0.5
  red_green_channel_swap:
    in_use: true
    p: 0.25

optimizer:
  name: SGD

loss:
  name: mixed
  kwargs:
    reduction: mean

lr_pretrained: 3.0e-05
lr_scratch: 3.0e-03

lr_scheduler:
  name: IterExponential
  kwargs:
    total_iter: 25000
    final_ratio: 3.0e-06
    warmup_steps: 1000

# Validation settings
validation:
  main_val_metric: abs_relative_difference
  main_val_metric_goal: minimize
  init_seed: 2024

eval:
  alignment: least_square
  align_max_res: null
  eval_metrics:
  - abs_relative_difference
  - squared_relative_difference
  - rmse_linear
  - rmse_log
  - log10
  - delta1_acc
  - delta2_acc
  - delta3_acc
  - i_rmse
  - silog_rmse
