name: mixed
prob_ls: [0.9, 0.1]
dataset_list:
- name: hypersim
  disp_name: hypersim_train
  dir: hypersim/data
  filenames: data_split/hypersim_train.txt
  resize_to_hw:
  - 480
  - 640
- name: vkitti2
  disp_name: vkitti2_train
  dir: vkitti2
  filenames: data_split/vkitti2_train.txt
  kitti_bm_crop: true
  valid_mask_crop: null